/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ISolarPlain3Bold: typeof import('~icons/solar/plain3-bold')['default']
    ISolarStarsMinimalisticLinear: typeof import('~icons/solar/stars-minimalistic-linear')['default']
  }
}
