/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ISolarAltArrowDownLinear: typeof import('~icons/solar/alt-arrow-down-linear')['default']
    ISolarAltArrowLeftLinear: typeof import('~icons/solar/alt-arrow-left-linear')['default']
    ISolarAltArrowRightLinear: typeof import('~icons/solar/alt-arrow-right-linear')['default']
    ISolarArrowRightLinear: typeof import('~icons/solar/arrow-right-linear')['default']
    ISolarChartSquareLinear: typeof import('~icons/solar/chart-square-linear')['default']
    ISolarChatRoundDotsLinear: typeof import('~icons/solar/chat-round-dots-linear')['default']
    ISolarChatRoundLineLinear: typeof import('~icons/solar/chat-round-line-linear')['default']
    ISolarCheckCircleBold: typeof import('~icons/solar/check-circle-bold')['default']
    ISolarCloseCircleBold: typeof import('~icons/solar/close-circle-bold')['default']
    ISolarCloseCircleLinear: typeof import('~icons/solar/close-circle-linear')['default']
    ISolarCodeSquareLinear: typeof import('~icons/solar/code-square-linear')['default']
    ISolarCopyLinear: typeof import('~icons/solar/copy-linear')['default']
    ISolarDownloadLinear: typeof import('~icons/solar/download-linear')['default']
    ISolarFileTextLinear: typeof import('~icons/solar/file-text-linear')['default']
    ISolarHamburgerMenuLinear: typeof import('~icons/solar/hamburger-menu-linear')['default']
    ISolarMagniferLinear: typeof import('~icons/solar/magnifer-linear')['default']
    ISolarMenuDotsLinear: typeof import('~icons/solar/menu-dots-linear')['default']
    ISolarPallete2Linear: typeof import('~icons/solar/pallete2-linear')['default']
    ISolarPaperclipLinear: typeof import('~icons/solar/paperclip-linear')['default']
    ISolarPenLinear: typeof import('~icons/solar/pen-linear')['default']
    ISolarPenNewSquareLinear: typeof import('~icons/solar/pen-new-square-linear')['default']
    ISolarRestartCircleLinear: typeof import('~icons/solar/restart-circle-linear')['default']
    ISolarRestartLinear: typeof import('~icons/solar/restart-linear')['default']
    ISolarStarsMinimalisticLinear: typeof import('~icons/solar/stars-minimalistic-linear')['default']
    ISolarTrashBinTrashLinear: typeof import('~icons/solar/trash-bin-trash-linear')['default']
  }
}
